name: Deploy Express.js App

on:
  push:
    branches:
      - main  # Change to your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Deploy to server via SSH
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.MULTIPLE_DOMAIN_SSH_HOST }}
        username: ${{ secrets.MULTIPLE_DOMAIN_SSH_USERNAME }}
        password: ${{ secrets.MULTIPLE_DOMAIN_SSH_PASSWORD }}
        port: ${{ secrets.MULTIPLE_DOMAIN_SSH_PORT }}
        script: |
          cd /var/www/express-ci-cd # Navigate to your app directory on the server
          git pull origin main # Pull the latest changes from your repository
          npm install # Install dependencies on the server
          # pm2 restart all # Restart your application using PM2 (or any other process manager you use)
